### ISSUE TITLE
연계 테이블 매핑 API schema 추가필요

### ISSUE THREAD

**Issue by goldnoh** [kayform/bwcontrol#18]
연계 테이블 매핑시 Public schema만 고려됨
schema별 분기 필요

**Comment by kayform** [comment]
schema 옵션 추가됨 b804d08
pg_add_ingest_table(**_'schema name'_**, 'table name', 'big data dbtype', '연계 모드', 'remark');
pg_del_ingest_table(**_'schema name'_**, 'table name');

topic name rule
table schema가 
public 일 경우 kafka-connect name + '.' + table name
public이 아닐경우  kafka-connect name + '.'  + schema name + '.' + table name
