### ISSUE TITLE
pg_del_ingest_column 동작오류

### ISSUE THREAD

**Issue by YONGWOOLEE** [kayform/bwcontrol#22]
wdb=# select pg_del_ingest_column ('public', 't', 'remark');
ERROR:  No such table.(-8)

wdb=# select * from col_mapps;
 reloid | column_name | colseq |        create_date         | create_user | remark
--------+-------------+--------+----------------------------+-------------+--------
 135778 | ckey        |      1 | 2017-04-05 09:51:45.325395 | robin       |
 135778 | cname       |      2 | 2017-04-05 10:39:05.430198 | robin       |
 135778 | remark      |      3 | 2017-04-05 10:56:51.343329 | robin       |
(3 rows)

**Comment by kayform** [comment]
Argument 처리오류 수정
