### ISSUE TITLE
[column_filter]select pg_del_ingest_column No such table 오류

### ISSUE THREAD

**Issue by YONGWOOLEE** [kayform/bwcontrol#24]
select pg_del_ingest_column('public', 'tttt', 'd'); 실행시
tttt 테이블이 존재하고 tbl_mapps에도 등록 되어 있으나 
ERROR:  No such table.(-8) 에러 발생

**Comment by gogoickgick** [comment]
테이블이 아니고 컬럼이 존재하지 않음. Error Message 수정 필요

**Comment by kayform** [comment]
Error Message 세분화 필요

**Comment by kayform** [comment]
error message 수정
